## Матричный метод

In [70]:
import numpy as np

* -5x+4y+1z=7
*   -8x−6y+3z=9
* -6x+9y+4z=6

In [78]:
K = np.array([[-5., 4., 1.], [-8., -6., 3.], [-6., 9., 4.]])
K

array([[-5.,  4.,  1.],
       [-8., -6.,  3.],
       [-6.,  9.,  4.]])

In [79]:
L = np.array([7., 9., 6.])
L = L[:, np.newaxis]
L

array([[7.],
       [9.],
       [6.]])

In [80]:
N = np.linalg.inv(K)
print(N)

[[-0.25123153 -0.03448276  0.08866995]
 [ 0.06896552 -0.06896552  0.03448276]
 [-0.5320197   0.10344828  0.30541872]]


In [81]:
A = np.linalg.solve(K, L)
print(A)

[[-1.53694581]
 [ 0.06896552]
 [-0.96059113]]


Ответ: -1.25, 0.17

In [83]:
B = (N.dot(L))
B

array([[-1.53694581],
       [ 0.06896552],
       [-0.96059113]])