## Свойства матричных вычислений

In [9]:
import numpy as np

In [10]:
l = [[11, 1, 6, 2], [34, 1, 4, 3], [42, 2, 11, 9], [4, 3, 1, 18]]
A = np.array(l)
A

array([[11,  1,  6,  2],
       [34,  1,  4,  3],
       [42,  2, 11,  9],
       [ 4,  3,  1, 18]])

In [11]:
k = [[11, 2, 1, 0], [12, 2, 13, 17], [36, 3, 11, 7], [2, 3, 1, 31]]
B = np.array(k)
B

array([[11,  2,  1,  0],
       [12,  2, 13, 17],
       [36,  3, 11,  7],
       [ 2,  3,  1, 31]])

In [12]:
k = [[8, 21, 15, 7], [2, 1, 4, 18], [4, 2, 12, 11], [5, 7, 1, 0]]
C = np.array(k)
C

array([[ 8, 21, 15,  7],
       [ 2,  1,  4, 18],
       [ 4,  2, 12, 11],
       [ 5,  7,  1,  0]])

Транспонирование матрицы:

In [13]:
A.transpose()

array([[11, 34, 42,  4],
       [ 1,  1,  2,  3],
       [ 6,  4, 11,  1],
       [ 2,  3,  9, 18]])

In [14]:
A.T

array([[11, 34, 42,  4],
       [ 1,  1,  2,  3],
       [ 6,  4, 11,  1],
       [ 2,  3,  9, 18]])

Дважды транспонированная матрица равна исходной матрице:

In [15]:
(A.T).T

array([[11,  1,  6,  2],
       [34,  1,  4,  3],
       [42,  2, 11,  9],
       [ 4,  3,  1, 18]])

Транспонирование суммы матриц равно сумме транспонированных матриц:

In [16]:
(A+B).T

array([[22, 46, 78,  6],
       [ 3,  3,  5,  6],
       [ 7, 17, 22,  2],
       [ 2, 20, 16, 49]])

In [17]:
A.T+B.T

array([[22, 46, 78,  6],
       [ 3,  3,  5,  6],
       [ 7, 17, 22,  2],
       [ 2, 20, 16, 49]])

Транспонирование произведения матриц равно произведению транспонированных
матриц расставленных в обратном порядке:

In [18]:
(A.dot(B)).T

array([[353, 536, 900, 152],
       [ 48,  91, 148,  71],
       [ 92,  94, 198,  72],
       [121, 138, 390, 616]])

In [19]:
(B.T).dot(A.T)

array([[353, 536, 900, 152],
       [ 48,  91, 148,  71],
       [ 92,  94, 198,  72],
       [121, 138, 390, 616]])

Транспонирование произведения матрицы на число равно произведению этого
числа на транспонированную матрицу:

In [20]:
t = 3

In [21]:
(t * A).T

array([[ 33, 102, 126,  12],
       [  3,   3,   6,   9],
       [ 18,  12,  33,   3],
       [  6,   9,  27,  54]])

In [22]:
t * (A.T)

array([[ 33, 102, 126,  12],
       [  3,   3,   6,   9],
       [ 18,  12,  33,   3],
       [  6,   9,  27,  54]])

Определители исходной и транспонированной матрицы совпадают:

In [23]:
format(np.linalg.det(A), '.9g')

'-2080'

In [24]:
format(np.linalg.det(A.T), '.9g')

'-2080'

Умножение матрицы на число


In [81]:
4 * A

array([[ 44,   4,  24,   8],
       [ 88,   8,  48,  16],
       [168,   8,  44,  36],
       [ 16,  12,   4,  72]])

Произведение единицы и любой заданной матрицы равно заданной матрице:

In [82]:
9 * A

array([[ 99,   9,  54,  18],
       [198,  18, 108,  36],
       [378,  18,  99,  81],
       [ 36,  27,   9, 162]])

Произведение нуля и любой матрицы равно нулевой матрице, размерность которой
равна исходной матрицы:

In [27]:
0 * A

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

 Произведение матрицы на сумму чисел равно сумме произведений матрицы на
каждое из этих чисел:

In [28]:
(2 + 3) * A

array([[ 55,   5,  30,  10],
       [170,   5,  20,  15],
       [210,  10,  55,  45],
       [ 20,  15,   5,  90]])

In [29]:
2 * A + 3 * A

array([[ 55,   5,  30,  10],
       [170,   5,  20,  15],
       [210,  10,  55,  45],
       [ 20,  15,   5,  90]])

Произведение матрицы на произведение двух чисел равно произведению второго
числа и заданной матрицы, умноженному на первое число:

In [30]:
(2 * 3) * A

array([[ 66,   6,  36,  12],
       [204,   6,  24,  18],
       [252,  12,  66,  54],
       [ 24,  18,   6, 108]])

In [31]:
2 * (3 * A)

array([[ 66,   6,  36,  12],
       [204,   6,  24,  18],
       [252,  12,  66,  54],
       [ 24,  18,   6, 108]])

Произведение суммы матриц на число равно сумме произведений этих матриц на
заданное число:

In [32]:
2 * (A + B)

array([[ 44,   6,  14,   4],
       [ 92,   6,  34,  40],
       [156,  10,  44,  32],
       [ 12,  12,   4,  98]])

In [33]:
2 * A + 2 * B

array([[ 44,   6,  14,   4],
       [ 92,   6,  34,  40],
       [156,  10,  44,  32],
       [ 12,  12,   4,  98]])

Сложение матриц


In [34]:
A + B

array([[22,  3,  7,  2],
       [46,  3, 17, 20],
       [78,  5, 22, 16],
       [ 6,  6,  2, 49]])

In [35]:
B + A

array([[22,  3,  7,  2],
       [46,  3, 17, 20],
       [78,  5, 22, 16],
       [ 6,  6,  2, 49]])

In [36]:
A + (B + C)

array([[30, 24, 22,  9],
       [48,  4, 21, 38],
       [82,  7, 34, 27],
       [11, 13,  3, 49]])

In [37]:
(A + B) + C

array([[30, 24, 22,  9],
       [48,  4, 21, 38],
       [82,  7, 34, 27],
       [11, 13,  3, 49]])

In [38]:
A + (-1)*A

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

Диаграмма матричного умножения


In [39]:
A.dot(B)

array([[353,  48,  92, 121],
       [536,  91,  94, 138],
       [900, 148, 198, 390],
       [152,  71,  72, 616]])

Ассоциативность умножения. Результат умножения матриц не зависит от порядка, в
котором будет выполняться эта операция:

In [40]:
A.dot(B.dot(C))

array([[ 3893,  8492,  6712,  4347],
       [ 5536, 12501,  9670,  6424],
       [10238, 22174, 16858, 11142],
       [ 4726,  7719,  4044,  3134]])

In [41]:
(A.dot(B)).dot(C)

array([[ 3893,  8492,  6712,  4347],
       [ 5536, 12501,  9670,  6424],
       [10238, 22174, 16858, 11142],
       [ 4726,  7719,  4044,  3134]])

Дистрибутивность умножения. Произведение матрицы на сумму матриц равно
сумме произведений матриц:

In [42]:
A.dot(B+C)

array([[ 477,  306,  335,  282],
       [ 841,  835,  659,  438],
       [1329, 1117,  977,  841],
       [ 284,  286,  174,  709]])

In [43]:
A.dot(B)+A.dot(C)

array([[ 477,  306,  335,  282],
       [ 841,  835,  659,  438],
       [1329, 1117,  977,  841],
       [ 284,  286,  174,  709]])

Умножение матриц в общем виде не коммутативно. Это означает, что для матриц не
выполняется правило независимости произведения от перестановки множителей:

In [44]:
A.dot(B)

array([[353,  48,  92, 121],
       [536,  91,  94, 138],
       [900, 148, 198, 390],
       [152,  71,  72, 616]])

In [45]:
B.dot(A)

array([[231,  15,  85,  37],
       [814,  91, 240, 453],
       [988,  82, 356, 306],
       [290, 100,  66, 580]])

Произведение заданной матрицы на единичную равно исходной матрице:

In [46]:
E = np.matrix('1 0 0 0; 0 1 0 0; 0 0 1 0; 0 0 0 1')
E.dot(A)

matrix([[11,  1,  6,  2],
        [34,  1,  4,  3],
        [42,  2, 11,  9],
        [ 4,  3,  1, 18]])

In [47]:
A.dot(E)

matrix([[11,  1,  6,  2],
        [34,  1,  4,  3],
        [42,  2, 11,  9],
        [ 4,  3,  1, 18]])

Произведение заданной матрицы на нулевую матрицу равно нулевой матрице:

In [48]:
Z = np.matrix('0 0 0 0; 0 0 0 0; 0 0 0 0; 0 0 0 0')
Z.dot(A)

matrix([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

In [49]:
A.dot(Z)

matrix([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

Определитель матрицы

In [50]:
np.linalg.det(A)

-2080.0000000000005

Определитель матрицы остается неизменным при ее транспонировании:

In [51]:
round(np.linalg.det(A), 3)

-2080.0

In [52]:
round(np.linalg.det(A.T), 3)

-2080.0

Если у матрицы есть строка или столбец, состоящие из нулей, то определитель
такой матрицы равен нулю:

In [56]:
N = np.matrix('1 0 1; 0 0 1; 21 2 1')
np.linalg.det(N)

-2.0

При перестановке строк матрицы знак ее определителя меняется на
противоположный:

In [57]:
N = np.matrix('2 1 4; 7 9 0; 34 12 1')
round(np.linalg.det(N), 3)

-877.0

In [58]:
N = np.matrix('11 12 12; 1 0 1; 21 14 6')
round(np.linalg.det(N), 3)

194.0

Если у матрицы есть две одинаковые строки, то ее определитель равен нулю:

In [59]:
N = np.matrix('1 0 1; 2 1 0; 15 5 2')
np.linalg.det(N)

-3.000000000000001

Если все элементы строки или столбца матрицы умножить на какое-то число, то и
определитель будет умножен на это число:

In [60]:
N = np.matrix('1 4 1; 2 1 6; 11 16 1')
k = 2
M = N.copy()
M[2, :] = k * M[2, :]
print(M)

[[ 1  4  1]
 [ 2  1  6]
 [22 32  2]]


In [61]:
det_N = round(np.linalg.det(N), 3)
det_M = round(np.linalg.det(M), 3)

In [62]:
det_N * k

364.0

In [63]:
det_M

364.0

Если все элементы строки или столбца можно представить как сумму двух
слагаемых, то определитель такой матрицы равен сумме определителей двух соответствующих
матриц:

In [64]:
C = A.copy()
C[1, :] += B[1, :]
print(C)

[[11  1  6  2]
 [46  3 17 20]
 [42  2 11  9]
 [ 4  3  1 18]]


In [65]:
A

array([[11,  1,  6,  2],
       [34,  1,  4,  3],
       [42,  2, 11,  9],
       [ 4,  3,  1, 18]])

In [66]:
B

array([[11,  2,  1,  0],
       [12,  2, 13, 17],
       [36,  3, 11,  7],
       [ 2,  3,  1, 31]])

In [67]:
round(np.linalg.det(C), 3)

3832.0

In [68]:
round(np.linalg.det(A), 3) + round(np.linalg.det(B), 3)

9916.0

Если к элементам одной строки прибавить элементы другой строки, умноженные на
одно и тоже число, то определитель матрицы не изменится:

In [69]:
C = A.copy()
C[1, :] = C[1, :] + 2 * C[0, :]
A

array([[11,  1,  6,  2],
       [34,  1,  4,  3],
       [42,  2, 11,  9],
       [ 4,  3,  1, 18]])

In [70]:
C

array([[11,  1,  6,  2],
       [56,  3, 16,  7],
       [42,  2, 11,  9],
       [ 4,  3,  1, 18]])

In [71]:
round(np.linalg.det(A), 3)

-2080.0

In [72]:
round(np.linalg.det(C), 3)

-2080.0

Если строка или столбец матрицы является линейной комбинацией других строк
(столбцов), то определитель такой матрицы равен нулю:

In [73]:
A[1, :] = A[0, :] + 2 * A[2, :]
round(np.linalg.det(A), 3)

-0.0

Если матрица содержит пропорциональные строки, то ее определитель равен нулю:

In [74]:
A[1, :] = 2 * A[0, :]
A

array([[11,  1,  6,  2],
       [22,  2, 12,  4],
       [42,  2, 11,  9],
       [ 4,  3,  1, 18]])

In [75]:
round(np.linalg.det(A), 3)

0.0

Обратная матрица

Обратная матрица обратной матрицы есть исходная матрица:

In [76]:
N = np.matrix('1 3; -1 4')
np.linalg.inv(N)

matrix([[ 0.57142857, -0.42857143],
        [ 0.14285714,  0.14285714]])

Обратная матрица транспонированной матрицы равна транспонированной матрице
от обратной матрицы:

In [77]:
np.linalg.inv(N.T)

matrix([[ 0.57142857,  0.14285714],
        [-0.42857143,  0.14285714]])

In [78]:
(np.linalg.inv(N)).T

matrix([[ 0.57142857,  0.14285714],
        [-0.42857143,  0.14285714]])

Обратная матрица произведения матриц равна произведению обратных матриц:

In [79]:
M = np.matrix('1. 8.; 2. 17.')
N = np.matrix('-4. 1.; 3. -9.')
np.linalg.inv(M.dot(N))

matrix([[-4.57575758,  2.15151515],
        [-1.3030303 ,  0.60606061]])

In [80]:
np.linalg.inv(N).dot(np.linalg.inv(M))

matrix([[-4.57575758,  2.15151515],
        [-1.3030303 ,  0.60606061]])